luku1 = int(input("Enter the first number\n"))
luku2 = int(input("Enter the second number\n"))
print("Total", luku1+luku2)
print("multiplication", luku1*luku2)
print("Minus", luku1 - luku2)
print("Division", luku1 / luku2)