luku1 = int(input("Anna eka luku\n"))
luku2 = int(input("Anna toka luku\n"))
print("Summa on", luku1+luku2)
print("Tulo on", luku1*luku2)
print("eka miinus toka on", luku1 - luku2)
print("eka jaettu toka on", luku1 / luku2)