number1 = int(input("Enter the first number\n"))
number2 = int(input("Enter the second number\n"))
print("Total",number1+number2)
print("multiplication", number1*number2)
print("Minus", number1 - number2)
print("Division", number1 / number2)